### ISSUE TITLE
Error when doing nixos-install --flake 'github:linuxmobile/kaku#linudev'

### ISSUE THREAD

**Issue by 4Gettt25** [linuxmobile/kaku#1]
So first of All the setup looks really nice, but everytime I get an error when trying the command mentioned in the title.![20230728_185741.jpg](https://github.com/linuxmobile/kaku/assets/126004052/cb62f969-d4a0-47d2-8625-27fc6da408b8)

Any idea why this could be happening?

**Comment by linuxmobile** [comment]
> So first of All the setup looks really nice, but everytime I get an error when trying the command mentioned in the title

idk why this. But you can try : 
```sh
pkgs.latest.rustChannels.stable.rust
pkgs.latest.rustChannels.stable.rust-src
```

**Comment by 4Gettt25** [comment]
Where would I need to put this in?

**Comment by linuxmobile** [comment]
> Where would I need to put this in?

I updated the guide, try again... adding to this, it's not a tutorial it's my dotfiles. learn nixos if necessary
