### ISSUE TITLE
Nix Hardware Generate Error

### ISSUE THREAD

**Issue by Marcus-Arcadius** [linuxmobile/kaku#11]
Keeps saying unrecognized argument

![PXL_20240831_110831666.jpg](https://github.com/user-attachments/assets/c7b7953d-4fe5-4f90-87ae-39f1d28c2648)

**Comment by linuxmobile** [comment]
Did you try to search for the command? For the next time there is an issue, try to upload the information well, and detail a little more.  The capture you uploaded is horrible.

![Screenshot from 2024-08-31 11-26-27](https://github.com/user-attachments/assets/45bc94a9-2738-4282-951d-894a68fb2167)
