### ISSUE TITLE
Eww & foot issue

### ISSUE THREAD

**Issue by xaolanx** [linuxmobile/kaku#12]
I know this is your personal configs, I would be very grateful if you would share the eww and foot config because theme.ini & eww conf were not found

**Comment by linuxmobile** [comment]
> I know this is your personal configs, I would be very grateful if you would share the eww and foot config because theme.ini & eww conf were not found

eww config is not posible, I would have to pass the entire config to nix syntax. And foot theme, take any foot theme, and be happy! Like catppuccin, gruvbox, etc.
