### ISSUE TITLE
xwaylandvideobridge failed to build

### ISSUE THREAD

**Issue by 2Epik4u** [linuxmobile/kaku#2]
when adding the xwaylandvideobridge package, it gives me this error when trying to build
```
error: hash mismatch in fixed-output derivation '/nix/store/wwh62binq619s84ygzr8ylwklv2v0xgw-source.drv':
         specified: sha256-enGDIPGdEA9DaqIiVUprdnGuuuQ/B2dq8H7nnid61QE=
            got:    sha256-Wzd48cIB/MCbzjBBfdmUfjA43oG0jtg7tWFl91FaDtk=
error: 1 dependencies of derivation '/nix/store/dqy5c64g2jpsvyvqwarhkwn8q32wd2jd-xwaylandvideobridge-unstable-2023-05-28.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0briy8i0snyz1xqi1kgrkdr5b1nsis2v-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mnz89v2c8l94qa8yw86z6jsidkic0c3s-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/94anjfll1r6bfw9ym0xmisj39hhllbxf-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/anazx8m2z2dm8j4m0vw1xxcfhw01yci2-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vm23kiydmy2wwdl1xzpfij57cwfg34vk-nixos-system-justin-nixos-23.11.20230813.100a155.drv' failed to build
```

**Comment by linuxmobile** [comment]
> specified: sha256-enGDIPGdEA9DaqIiVUprdnGuuuQ/B2dq8H7nnid61QE=
>             got:    sha256-Wzd48cIB/MCbzjBBfdmUfjA43oG0jtg7tWFl91FaDtk=

Fix this.

**Comment by 2Epik4u** [comment]
Ok i changed it in a fork and it built sucessfully should i make a pull request

**Comment by linuxmobile** [comment]
> Ok i changed it in a fork and it built sucessfully should i make a pull request
idk, **in my build it's working fine**.

**Comment by Lxp1zero** [comment]
> Ok i changed it in a fork and it built sucessfully should i make a pull request

Hey hello, how did solve this ? By fork, how do I add one ? Sorry I'm a newbie

**Comment by linuxmobile** [comment]
> > Ok i changed it in a fork and it built sucessfully should i make a pull request
> 
> Hey hello, how did solve this ? By fork, how do I add one ? Sorry I'm a newbie

Replace the hash. But u can use the oficial nixpkgs now
