### ISSUE TITLE
cannot find flakes#kaku

### ISSUE THREAD

**Issue by brownjeesus** [linuxmobile/kaku#4]
I'm running the command ``nixos-install --flake kaku#linudev`` and it's returning me the following error cannot find the following flake in the flake registries, totally new to nix and nixos

**Comment by linuxmobile** [comment]
> I'm running the command `nixos-install --flake kaku#linudev` and it's returning me the following error cannot find the following flake in the flake registries, totally new to nix and nixos

You need to learn some Nix/NixOS things. Replace it with your `hostname` settings. It's a **GUIDE** not a tutorial
