### ISSUE TITLE
Unrecognised argument 

### ISSUE THREAD

**Issue by Lxp1zero** [linuxmobile/kaku#6]
Unrecognised argument after generating "sudo nixos-generate-config --dir --force /mnt/etc/nixos/hosts/aesthetic"

**Comment by linuxmobile** [comment]
Study about nixos, and don't open issues like this. Goodbye

**Comment by Lxp1zero** [comment]
> Study about nixos, and don't open issues like this. Goodbye
Doing

nixos-generate-config --force --dir /mnt/etc/nixos/hosts/aesthetic worked for me
