### ISSUE TITLE
How to deal with hash mismatch 

### ISSUE THREAD

**Issue by Lxp1zero** [linuxmobile/kaku#7]
I tried adding nix packages manually tho however it still returns with error  as the author suggested 
![IMG20240219164714](https://github.com/linuxmobile/kaku/assets/126608444/34a3b0ce-2d36-4f76-a8e4-89fce2017662)

**Comment by linuxmobile** [comment]
Stop open issues. Read the fucking docs.

**Comment by Lxp1zero** [comment]
Yes no need to furious you could have just tell the solution with 3 or 4 sentence
